// /exceptdestruct.cpp
class SomeObject {
public:
  SomeObject() {
    cout << "calling the constructor"
         << '\n'; };
  ~SomeObject() {
    cout <<  "calling the destructor"
         << '\n'; };
};
    /* ... */
// /exceptdestruct.cpp
  try {
    SomeObject obj;
    cout << "Inside the nested scope" << '\n';
    throw(1);
  } catch (...) {
    cout << "Exception caught" << '\n';
  }
